### ISSUE TITLE
Empty read; connection dead

### ISSUE THREAD

**Issue by mrahmadt** [minkphp/Mink#832]
Hello Team

I'm using Mink with chromedriver and things are working fine. however, "randomly" in multiple requests I'm getting the below error and I'm not able to figure out what is the issue. I search all around the internet and no clear answer

```
local.ERROR: Empty read; connection dead? {"exception":"[object] (WebSocket\\ConnectionException(code: 1025): Empty read; connection dead? at /home/me/project/vendor/textalk/websocket/lib/Base.php:484)
[stacktrace]
#0 /home/me/project/vendor/textalk/websocket/lib/Base.php(459): WebSocket\\Base->throwException()
#1 /home/me/project/vendor/textalk/websocket/lib/Base.php(287): WebSocket\\Base->read()
#2 /home/me/project/vendor/textalk/websocket/lib/Base.php(235): WebSocket\\Base->receiveFragment()
#3 /home/me/project/vendor/dmore/chrome-mink-driver/src/DevToolsConnection.php(100): WebSocket\\Base->receive()
#4 /home/me/project/vendor/dmore/chrome-mink-driver/src/DevToolsConnection.php(85): DMore\\ChromeDriver\\DevToolsConnection->waitFor()
#5 /home/me/project/vendor/dmore/chrome-mink-driver/src/ChromeDriver.php(1456): DMore\\ChromeDriver\\DevToolsConnection->send()
#6 /home/me/project/vendor/dmore/chrome-mink-driver/src/ChromeDriver.php(1102): DMore\\ChromeDriver\\ChromeDriver->runScript()
#7 /home/me/project/vendor/dmore/chrome-mink-driver/src/ChromeDriver.php(1386): DMore\\ChromeDriver\\ChromeDriver->evaluateScript()
#8 /home/me/project/vendor/dmore/chrome-mink-driver/src/ChromeDriver.php(1263): DMore\\ChromeDriver\\ChromeDriver->runScriptOnXpathElement()
#9 /home/me/project/vendor/dmore/chrome-mink-driver/src/ChromeDriver.php(652): DMore\\ChromeDriver\\ChromeDriver->getElementProperty()
#10 /home/me/project/vendor/dmore/chrome-mink-driver/src/ChromeDriver.php(484): DMore\\ChromeDriver\\ChromeDriver->getHtml()
#11 /home/me/project/app/Jobs/BrowserRequest.php(105): DMore\\ChromeDriver\\ChromeDriver->getContent()
.....
#47 {main}
```

for chrome, I'm using https://github.com/Zenika/alpine-chrome container with this command
`
docker container run -d -p 9222:9222 zenika/alpine-chrome --no-sandbox --remote-debugging-address=0.0.0.0 --remote-debugging-port=9222
`

PHP
```
# php -v
PHP 8.1.2 (cli) (built: Jul 21 2022 12:10:37) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.2, Copyright (c) Zend Technologies
    with Zend OPcache v8.1.2, Copyright (c), by Zend Technologies
```

**Comment by stof** [comment]
The stack trace indicates that the error comes from the `dmore/chrome-mink-driver` package, so you should report that to their issue tracker (which is at https://gitlab.com/behat-chrome/chrome-mink-driver/-/issues)
